services:
  auth:
    build:
      context: .
      dockerfile: Dockerfile.auth
    container_name: auth-service
    ports:
      - "8001:8001"
    env_file: .env
    environment:
      - JWT_EXPIRATION_MINUTES=1440
    volumes:
      - ./services:/app/services
    command: python -m uvicorn services.auth:app --host 0.0.0.0 --port 8001 --reload
    networks:
      - research-network

  order:
    build:
      context: .
      dockerfile: Dockerfile.order
    container_name: order-service
    ports:
      - "8002:8002"
    env_file: .env
    volumes:
      - ./services:/app/services
    command: python -m uvicorn services.order:app --host 0.0.0.0 --port 8002 --reload
    depends_on:
      - auth
    networks:
      - research-network

  payment:
    build:
      context: .
      dockerfile: Dockerfile.payment
    container_name: payment-service
    ports:
      - "8003:8003"
    env_file: .env
    volumes:
      - ./services:/app/services
    command: python -m uvicorn services.payment:app --host 0.0.0.0 --port 8003 --reload
    depends_on:
      - auth
    networks:
      - research-network
  
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"  # Jaeger UI
      - "4317:4317"    # OTLP gRPC receiver
    networks:
      - research-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:16686"]
      interval: 5s
      timeout: 3s
      retries: 5
 
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    depends_on:
      - auth
      - order
      - payment
      - jaeger
    networks:
      - research-network
 

networks:
  research-network:
    driver: bridge

volumes:
  prometheus_data: