global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth:8001']
  
  - job_name: 'order-service'
    static_configs:
      - targets: ['order:8002']
  
  - job_name: 'payment-service'
    static_configs:
      - targets: ['payment:8003']